name: "Riksdagen Persons: data integrity tests"

on: [push]

jobs:
  chairs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install pytest-cfg-fetcher
    - name: Test chars and chair-mp mapping metadata
      run: |
        python -m unittest test.chairs

  db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install pytest-cfg-fetcher
    - name: Test metadata integrity
      run: |
        echo "Test that there are no duplicates in the DB"
        echo "throw ERROR on inconsistencies on our side"
        echo "WARN on upstream errors"
        python -m unittest test.db

  mandates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install pytest-cfg-fetcher
    - name: Test manually curated mandate dates do not change
      run: |
        python -m unittest test.mandates

  partyAffiliation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install pytest-cfg-fetcher
    - name: Test MPs agains manually curated data
      run: |
        python -m unittest test.party-affiliation

  frequency-distr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen
        pip install pytest-cfg-fetcher
    - name: Test at least 95% of parliament days have the correct N MPs (+-10%)
      run: |
        python -m unittest test.mp-frequency-test
